//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseCaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaseCaja()
        {
            this.Gastos = new HashSet<Gastos>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> fechaApertura { get; set; }
        public Nullable<int> idUsuarioApertura { get; set; }
        public Nullable<decimal> valorBase { get; set; }
        public Nullable<System.DateTime> fechaCierre { get; set; }
        public Nullable<int> idUsuarioCierre { get; set; }
        public string estadoBase { get; set; }
        public Nullable<int> idSedeBAse { get; set; }
    
        public virtual Sede Sede { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gastos> Gastos { get; set; }
    }
}
