//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compras()
        {
            this.ArchivoCompras = new HashSet<ArchivoCompras>();
            this.DetalleCompra = new HashSet<DetalleCompra>();
            this.PagosCompras = new HashSet<PagosCompras>();
        }
    
        public int id { get; set; }
        public string facturaCompra { get; set; }
        public Nullable<System.DateTime> fechaCompra { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public Nullable<decimal> subtotalCompra { get; set; }
        public Nullable<decimal> ivaCompra { get; set; }
        public Nullable<decimal> totalCompra { get; set; }
        public Nullable<decimal> valorPagadoCompra { get; set; }
        public Nullable<decimal> saldoCompra { get; set; }
        public Nullable<System.Guid> guidCompra { get; set; }
        public Nullable<int> idSede { get; set; }
        public string extencionArchivo { get; set; }
        public decimal totalDescuento { get; set; }
        public Nullable<int> idEstadoAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivoCompras> ArchivoCompras { get; set; }
        public virtual EstadoAI EstadoAI { get; set; }
        public virtual Sede Sede { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCompra> DetalleCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagosCompras> PagosCompras { get; set; }
    }
}
