//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleCompra()
        {
            this.R_ProductoCompra = new HashSet<R_ProductoCompra>();
        }
    
        public int id { get; set; }
        public int idCompra { get; set; }
        public int idInventario { get; set; }
        public decimal cantidad { get; set; }
        public decimal precioUnitario { get; set; }
        public decimal porcentajeDescuento { get; set; }
        public decimal valorDescuento { get; set; }
        public decimal porcentajeIva { get; set; }
        public decimal valorIva { get; set; }
        public decimal totalDetalle { get; set; }
        public decimal costoUnidad { get; set; }
        public decimal rango1 { get; set; }
        public decimal rango2 { get; set; }
        public int estadoCosto { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> idInventarioTotal { get; set; }
    
        public virtual Compras Compras { get; set; }
        public virtual InventarioTotal InventarioTotal { get; set; }
        public virtual Producto Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_ProductoCompra> R_ProductoCompra { get; set; }
    }
}
