//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        public int id { get; set; }
        public int idVenta { get; set; }
        public int idPrecios { get; set; }
        public int idInventario { get; set; }
        public int idSede { get; set; }
        public string descripcionProducto { get; set; }
        public decimal cantidadDetalle { get; set; }
        public decimal costoUnidad { get; set; }
        public decimal precioVenta { get; set; }
        public Nullable<int> idInventarioTotal { get; set; }
        public Nullable<decimal> porcentageIVA { get; set; }
    
        public virtual InventarioTotal InventarioTotal { get; set; }
        public virtual Inventario Inventario { get; set; }
        public virtual Precios Precios { get; set; }
        public virtual Sede Sede { get; set; }
    }
}
