//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SistemaPOSEntities : DbContext
    {
        public SistemaPOSEntities()
            : base("name=SistemaPOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminControl> AdminControl { get; set; }
        public virtual DbSet<ArchivoCompras> ArchivoCompras { get; set; }
        public virtual DbSet<AutorizacionFacturacionElectronica> AutorizacionFacturacionElectronica { get; set; }
        public virtual DbSet<AutorizacionPC> AutorizacionPC { get; set; }
        public virtual DbSet<BaseCaja> BaseCaja { get; set; }
        public virtual DbSet<Bodega> Bodega { get; set; }
        public virtual DbSet<Bolsillo> Bolsillo { get; set; }
        public virtual DbSet<CategoriaProducto> CategoriaProducto { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<CompraActiva> CompraActiva { get; set; }
        public virtual DbSet<Compras> Compras { get; set; }
        public virtual DbSet<ConsecutivoFactura> ConsecutivoFactura { get; set; }
        public virtual DbSet<ConsecutivoPedido> ConsecutivoPedido { get; set; }
        public virtual DbSet<ConsecutivoRecibo> ConsecutivoRecibo { get; set; }
        public virtual DbSet<ConsecutivoVentaUsado> ConsecutivoVentaUsado { get; set; }
        public virtual DbSet<DestapeProducto> DestapeProducto { get; set; }
        public virtual DbSet<DetalleCompra> DetalleCompra { get; set; }
        public virtual DbSet<DetalleOrdenFabrica> DetalleOrdenFabrica { get; set; }
        public virtual DbSet<DetallePedido> DetallePedido { get; set; }
        public virtual DbSet<DetalleTraslado> DetalleTraslado { get; set; }
        public virtual DbSet<DetalleVenta> DetalleVenta { get; set; }
        public virtual DbSet<DetalleVentaActiva> DetalleVentaActiva { get; set; }
        public virtual DbSet<EstadoAI> EstadoAI { get; set; }
        public virtual DbSet<EstadoInventario> EstadoInventario { get; set; }
        public virtual DbSet<EstadoPedido> EstadoPedido { get; set; }
        public virtual DbSet<FacturaSoftware> FacturaSoftware { get; set; }
        public virtual DbSet<Gastos> Gastos { get; set; }
        public virtual DbSet<GuidTraslados> GuidTraslados { get; set; }
        public virtual DbSet<Impresora> Impresora { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<InventarioTotal> InventarioTotal { get; set; }
        public virtual DbSet<LibroDiario> LibroDiario { get; set; }
        public virtual DbSet<Licencia> Licencia { get; set; }
        public virtual DbSet<ListaPrecios> ListaPrecios { get; set; }
        public virtual DbSet<Merma> Merma { get; set; }
        public virtual DbSet<Modulos> Modulos { get; set; }
        public virtual DbSet<OrdenFabrica> OrdenFabrica { get; set; }
        public virtual DbSet<OrdenServicio> OrdenServicio { get; set; }
        public virtual DbSet<PagosCompras> PagosCompras { get; set; }
        public virtual DbSet<PagosCreditoTienda> PagosCreditoTienda { get; set; }
        public virtual DbSet<PedidoActivo> PedidoActivo { get; set; }
        public virtual DbSet<Pedidos> Pedidos { get; set; }
        public virtual DbSet<PermisoModulo> PermisoModulo { get; set; }
        public virtual DbSet<PermisoSubModulo> PermisoSubModulo { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<Precios> Precios { get; set; }
        public virtual DbSet<Presentacion> Presentacion { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<R_ClienteVendedor> R_ClienteVendedor { get; set; }
        public virtual DbSet<R_PedidoVenta> R_PedidoVenta { get; set; }
        public virtual DbSet<R_ProductoCompra> R_ProductoCompra { get; set; }
        public virtual DbSet<R_VentaCliente> R_VentaCliente { get; set; }
        public virtual DbSet<R_VentaUsuario> R_VentaUsuario { get; set; }
        public virtual DbSet<R_VentaVendedor> R_VentaVendedor { get; set; }
        public virtual DbSet<ReporteActualizacionEquipo> ReporteActualizacionEquipo { get; set; }
        public virtual DbSet<ReporteVisita> ReporteVisita { get; set; }
        public virtual DbSet<ResponsableOrdenFabrica> ResponsableOrdenFabrica { get; set; }
        public virtual DbSet<RutaActualizacionEquipo> RutaActualizacionEquipo { get; set; }
        public virtual DbSet<Sede> Sede { get; set; }
        public virtual DbSet<SedesAsignadas> SedesAsignadas { get; set; }
        public virtual DbSet<Semana> Semana { get; set; }
        public virtual DbSet<SubModulos> SubModulos { get; set; }
        public virtual DbSet<TablaVentas> TablaVentas { get; set; }
        public virtual DbSet<TipoArticulo> TipoArticulo { get; set; }
        public virtual DbSet<TipoGasto> TipoGasto { get; set; }
        public virtual DbSet<TipoMedida> TipoMedida { get; set; }
        public virtual DbSet<TipoMerma> TipoMerma { get; set; }
        public virtual DbSet<TipoServicio> TipoServicio { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Traslados> Traslados { get; set; }
        public virtual DbSet<Tutoriales> Tutoriales { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Vendedor> Vendedor { get; set; }
        public virtual DbSet<VentaActiva> VentaActiva { get; set; }
        public virtual DbSet<VersionSoftware> VersionSoftware { get; set; }
        public virtual DbSet<BuscadorProducto> BuscadorProducto { get; set; }
        public virtual DbSet<R_DetalleVenta> R_DetalleVenta { get; set; }
        public virtual DbSet<R_PagoCredito> R_PagoCredito { get; set; }
        public virtual DbSet<V_ArchivoCompras> V_ArchivoCompras { get; set; }
        public virtual DbSet<v_CategoriaProducto> v_CategoriaProducto { get; set; }
        public virtual DbSet<V_Ciudades> V_Ciudades { get; set; }
        public virtual DbSet<V_Cliente> V_Cliente { get; set; }
        public virtual DbSet<V_Compras> V_Compras { get; set; }
        public virtual DbSet<V_CostoInventario> V_CostoInventario { get; set; }
        public virtual DbSet<V_CuentasPC> V_CuentasPC { get; set; }
        public virtual DbSet<V_DetalleCaja> V_DetalleCaja { get; set; }
        public virtual DbSet<V_DetalleCompra> V_DetalleCompra { get; set; }
        public virtual DbSet<V_DetallePedico_Venta> V_DetallePedico_Venta { get; set; }
        public virtual DbSet<V_DetallePedido> V_DetallePedido { get; set; }
        public virtual DbSet<V_DetalleTraslado> V_DetalleTraslado { get; set; }
        public virtual DbSet<V_FacturasCredito> V_FacturasCredito { get; set; }
        public virtual DbSet<V_Gastos> V_Gastos { get; set; }
        public virtual DbSet<V_InformeDetalleVenta> V_InformeDetalleVenta { get; set; }
        public virtual DbSet<V_Inventario> V_Inventario { get; set; }
        public virtual DbSet<V_InventarioTotal> V_InventarioTotal { get; set; }
        public virtual DbSet<V_LibroDiario> V_LibroDiario { get; set; }
        public virtual DbSet<V_ListaPrecio> V_ListaPrecio { get; set; }
        public virtual DbSet<V_ListaPrecios> V_ListaPrecios { get; set; }
        public virtual DbSet<V_ListaVentaCategoria> V_ListaVentaCategoria { get; set; }
        public virtual DbSet<V_Merma> V_Merma { get; set; }
        public virtual DbSet<V_PagoCP> V_PagoCP { get; set; }
        public virtual DbSet<V_PagosCreditoTienda> V_PagosCreditoTienda { get; set; }
        public virtual DbSet<V_pd> V_pd { get; set; }
        public virtual DbSet<V_Pedido> V_Pedido { get; set; }
        public virtual DbSet<V_Precios> V_Precios { get; set; }
        public virtual DbSet<V_Presentacion> V_Presentacion { get; set; }
        public virtual DbSet<V_Producto> V_Producto { get; set; }
        public virtual DbSet<v_productoVenta> v_productoVenta { get; set; }
        public virtual DbSet<V_Proveedor> V_Proveedor { get; set; }
        public virtual DbSet<V_R_VentaCliente> V_R_VentaCliente { get; set; }
        public virtual DbSet<V_Rutero> V_Rutero { get; set; }
        public virtual DbSet<V_SedesAsignadas> V_SedesAsignadas { get; set; }
        public virtual DbSet<V_TablaVentas> V_TablaVentas { get; set; }
        public virtual DbSet<V_TipoGasto> V_TipoGasto { get; set; }
        public virtual DbSet<V_TipoMedida> V_TipoMedida { get; set; }
        public virtual DbSet<V_TipoMerma> V_TipoMerma { get; set; }
        public virtual DbSet<V_TotalVentasDetalle> V_TotalVentasDetalle { get; set; }
        public virtual DbSet<V_Traslados> V_Traslados { get; set; }
        public virtual DbSet<v_Usuario> v_Usuario { get; set; }
        public virtual DbSet<V_Vendedor> V_Vendedor { get; set; }
    
        public virtual int EliminarArchivoComra(Nullable<int> idCompra)
        {
            var idCompraParameter = idCompra.HasValue ?
                new ObjectParameter("idCompra", idCompra) :
                new ObjectParameter("idCompra", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarArchivoComra", idCompraParameter);
        }
    
        public virtual int EliminarConsecutivoActivo(Nullable<int> idConsecutivo)
        {
            var idConsecutivoParameter = idConsecutivo.HasValue ?
                new ObjectParameter("idConsecutivo", idConsecutivo) :
                new ObjectParameter("idConsecutivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarConsecutivoActivo", idConsecutivoParameter);
        }
    
        public virtual int EliminarDetalleVEnta(Nullable<int> idVenta)
        {
            var idVentaParameter = idVenta.HasValue ?
                new ObjectParameter("idVenta", idVenta) :
                new ObjectParameter("idVenta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarDetalleVEnta", idVentaParameter);
        }
    
        public virtual int EliminarPagoCompras(Nullable<int> idCompra)
        {
            var idCompraParameter = idCompra.HasValue ?
                new ObjectParameter("idCompra", idCompra) :
                new ObjectParameter("idCompra", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarPagoCompras", idCompraParameter);
        }
    
        public virtual int EliminarPedido(Nullable<System.Guid> guidPedido)
        {
            var guidPedidoParameter = guidPedido.HasValue ?
                new ObjectParameter("guidPedido", guidPedido) :
                new ObjectParameter("guidPedido", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarPedido", guidPedidoParameter);
        }
    
        public virtual int EliminarVenta_app(Nullable<int> idVenta)
        {
            var idVentaParameter = idVenta.HasValue ?
                new ObjectParameter("idVenta", idVenta) :
                new ObjectParameter("idVenta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarVenta_app", idVentaParameter);
        }
    
        public virtual int EstadoVentaAnulado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EstadoVentaAnulado");
        }
    
        public virtual int EstadoVentaCancelado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EstadoVentaCancelado");
        }
    
        public virtual int EstadoVentaPendiente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EstadoVentaPendiente");
        }
    
        public virtual int FacturarPedido(Nullable<int> idVenta, Nullable<System.Guid> guid)
        {
            var idVentaParameter = idVenta.HasValue ?
                new ObjectParameter("idVenta", idVenta) :
                new ObjectParameter("idVenta", typeof(int));
    
            var guidParameter = guid.HasValue ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FacturarPedido", idVentaParameter, guidParameter);
        }
    
        public virtual ObjectResult<InformeVentasVendedor_dia_Result> InformeVentasVendedor_dia(Nullable<int> month, Nullable<int> day, Nullable<int> year)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var dayParameter = day.HasValue ?
                new ObjectParameter("day", day) :
                new ObjectParameter("day", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InformeVentasVendedor_dia_Result>("InformeVentasVendedor_dia", monthParameter, dayParameter, yearParameter);
        }
    
        public virtual ObjectResult<InformeVentasVendedor_mes_Result> InformeVentasVendedor_mes(Nullable<int> month, Nullable<int> year)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InformeVentasVendedor_mes_Result>("InformeVentasVendedor_mes", monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<InformeVentasVendedor_year_Result> InformeVentasVendedor_year(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InformeVentasVendedor_year_Result>("InformeVentasVendedor_year", yearParameter);
        }
    
        public virtual int insertAutorizacionFacturaElectronica(Nullable<int> idEmpresa, string prefijo, string resolucion, string fechaAvilitacion, string rango)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(int));
    
            var prefijoParameter = prefijo != null ?
                new ObjectParameter("prefijo", prefijo) :
                new ObjectParameter("prefijo", typeof(string));
    
            var resolucionParameter = resolucion != null ?
                new ObjectParameter("resolucion", resolucion) :
                new ObjectParameter("resolucion", typeof(string));
    
            var fechaAvilitacionParameter = fechaAvilitacion != null ?
                new ObjectParameter("fechaAvilitacion", fechaAvilitacion) :
                new ObjectParameter("fechaAvilitacion", typeof(string));
    
            var rangoParameter = rango != null ?
                new ObjectParameter("rango", rango) :
                new ObjectParameter("rango", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertAutorizacionFacturaElectronica", idEmpresaParameter, prefijoParameter, resolucionParameter, fechaAvilitacionParameter, rangoParameter);
        }
    
        public virtual int InsertMerma(Nullable<int> idTipoMerma, Nullable<int> idUsuario, Nullable<int> idInventarioTotal, Nullable<int> idInventario, Nullable<System.DateTime> fechaMerma, Nullable<decimal> cantidadMerma, string observacion)
        {
            var idTipoMermaParameter = idTipoMerma.HasValue ?
                new ObjectParameter("idTipoMerma", idTipoMerma) :
                new ObjectParameter("idTipoMerma", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var idInventarioTotalParameter = idInventarioTotal.HasValue ?
                new ObjectParameter("idInventarioTotal", idInventarioTotal) :
                new ObjectParameter("idInventarioTotal", typeof(int));
    
            var idInventarioParameter = idInventario.HasValue ?
                new ObjectParameter("idInventario", idInventario) :
                new ObjectParameter("idInventario", typeof(int));
    
            var fechaMermaParameter = fechaMerma.HasValue ?
                new ObjectParameter("fechaMerma", fechaMerma) :
                new ObjectParameter("fechaMerma", typeof(System.DateTime));
    
            var cantidadMermaParameter = cantidadMerma.HasValue ?
                new ObjectParameter("cantidadMerma", cantidadMerma) :
                new ObjectParameter("cantidadMerma", typeof(decimal));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("observacion", observacion) :
                new ObjectParameter("observacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertMerma", idTipoMermaParameter, idUsuarioParameter, idInventarioTotalParameter, idInventarioParameter, fechaMermaParameter, cantidadMermaParameter, observacionParameter);
        }
    
        public virtual ObjectResult<P_Rutero_Result> P_Rutero(Nullable<int> day, Nullable<int> month, Nullable<int> year)
        {
            var dayParameter = day.HasValue ?
                new ObjectParameter("day", day) :
                new ObjectParameter("day", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Rutero_Result>("P_Rutero", dayParameter, monthParameter, yearParameter);
        }
    
        public virtual int Reiniciar_DB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Reiniciar_DB");
        }
    
        public virtual ObjectResult<SelectAlistamiento_Result> SelectAlistamiento(Nullable<int> idVendedor, Nullable<int> idEstado, Nullable<int> day, Nullable<int> month, Nullable<int> year)
        {
            var idVendedorParameter = idVendedor.HasValue ?
                new ObjectParameter("idVendedor", idVendedor) :
                new ObjectParameter("idVendedor", typeof(int));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("idEstado", idEstado) :
                new ObjectParameter("idEstado", typeof(int));
    
            var dayParameter = day.HasValue ?
                new ObjectParameter("Day", day) :
                new ObjectParameter("Day", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAlistamiento_Result>("SelectAlistamiento", idVendedorParameter, idEstadoParameter, dayParameter, monthParameter, yearParameter);
        }
    
        public virtual int SumarGastosCajaDia(Nullable<System.DateTime> fechaApertura, Nullable<System.DateTime> fechaActual, Nullable<System.TimeSpan> horaApertura, Nullable<System.TimeSpan> horaActual, Nullable<int> bolsillo, ObjectParameter gasto)
        {
            var fechaAperturaParameter = fechaApertura.HasValue ?
                new ObjectParameter("FechaApertura", fechaApertura) :
                new ObjectParameter("FechaApertura", typeof(System.DateTime));
    
            var fechaActualParameter = fechaActual.HasValue ?
                new ObjectParameter("FechaActual", fechaActual) :
                new ObjectParameter("FechaActual", typeof(System.DateTime));
    
            var horaAperturaParameter = horaApertura.HasValue ?
                new ObjectParameter("HoraApertura", horaApertura) :
                new ObjectParameter("HoraApertura", typeof(System.TimeSpan));
    
            var horaActualParameter = horaActual.HasValue ?
                new ObjectParameter("HoraActual", horaActual) :
                new ObjectParameter("HoraActual", typeof(System.TimeSpan));
    
            var bolsilloParameter = bolsillo.HasValue ?
                new ObjectParameter("Bolsillo", bolsillo) :
                new ObjectParameter("Bolsillo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SumarGastosCajaDia", fechaAperturaParameter, fechaActualParameter, horaAperturaParameter, horaActualParameter, bolsilloParameter, gasto);
        }
    
        public virtual int V_ReiniciarDB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("V_ReiniciarDB");
        }
    }
}
