//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SistemaPOSEntities : DbContext
    {
        public SistemaPOSEntities()
            : base("name=SistemaPOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminControl> AdminControl { get; set; }
        public virtual DbSet<ArchivoCompras> ArchivoCompras { get; set; }
        public virtual DbSet<AutorizacionFacturacionElectronica> AutorizacionFacturacionElectronica { get; set; }
        public virtual DbSet<AutorizacionPC> AutorizacionPC { get; set; }
        public virtual DbSet<BaseCaja> BaseCaja { get; set; }
        public virtual DbSet<Bodega> Bodega { get; set; }
        public virtual DbSet<Bolsillo> Bolsillo { get; set; }
        public virtual DbSet<CategoriaProducto> CategoriaProducto { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<CompraActiva> CompraActiva { get; set; }
        public virtual DbSet<Compras> Compras { get; set; }
        public virtual DbSet<ConsecutivoFactura> ConsecutivoFactura { get; set; }
        public virtual DbSet<ConsecutivoPedido> ConsecutivoPedido { get; set; }
        public virtual DbSet<ConsecutivoRecibo> ConsecutivoRecibo { get; set; }
        public virtual DbSet<ConsecutivoVentaUsado> ConsecutivoVentaUsado { get; set; }
        public virtual DbSet<DestapeProducto> DestapeProducto { get; set; }
        public virtual DbSet<DetalleCompra> DetalleCompra { get; set; }
        public virtual DbSet<DetalleOrdenFabrica> DetalleOrdenFabrica { get; set; }
        public virtual DbSet<DetallePedido> DetallePedido { get; set; }
        public virtual DbSet<DetalleTraslado> DetalleTraslado { get; set; }
        public virtual DbSet<DetalleVenta> DetalleVenta { get; set; }
        public virtual DbSet<DetalleVentaActiva> DetalleVentaActiva { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<EstadoAI> EstadoAI { get; set; }
        public virtual DbSet<EstadoInventario> EstadoInventario { get; set; }
        public virtual DbSet<EstadoPedido> EstadoPedido { get; set; }
        public virtual DbSet<FacturaSoftware> FacturaSoftware { get; set; }
        public virtual DbSet<Gastos> Gastos { get; set; }
        public virtual DbSet<GuidTraslados> GuidTraslados { get; set; }
        public virtual DbSet<Impresora> Impresora { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<InventarioTotal> InventarioTotal { get; set; }
        public virtual DbSet<LibroDiario> LibroDiario { get; set; }
        public virtual DbSet<Licencia> Licencia { get; set; }
        public virtual DbSet<ListaPrecios> ListaPrecios { get; set; }
        public virtual DbSet<Merma> Merma { get; set; }
        public virtual DbSet<Modulos> Modulos { get; set; }
        public virtual DbSet<OrdenFabrica> OrdenFabrica { get; set; }
        public virtual DbSet<OrdenServicio> OrdenServicio { get; set; }
        public virtual DbSet<PagosCompras> PagosCompras { get; set; }
        public virtual DbSet<PagosCreditoTienda> PagosCreditoTienda { get; set; }
        public virtual DbSet<PedidoActivo> PedidoActivo { get; set; }
        public virtual DbSet<Pedidos> Pedidos { get; set; }
        public virtual DbSet<PermisoModulo> PermisoModulo { get; set; }
        public virtual DbSet<PermisoSubModulo> PermisoSubModulo { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<Precios> Precios { get; set; }
        public virtual DbSet<Presentacion> Presentacion { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<R_ClienteVendedor> R_ClienteVendedor { get; set; }
        public virtual DbSet<R_PedidoVenta> R_PedidoVenta { get; set; }
        public virtual DbSet<R_ProductoCompra> R_ProductoCompra { get; set; }
        public virtual DbSet<R_VentaCliente> R_VentaCliente { get; set; }
        public virtual DbSet<R_VentaUsuario> R_VentaUsuario { get; set; }
        public virtual DbSet<R_VentaVendedor> R_VentaVendedor { get; set; }
        public virtual DbSet<ReporteActualizacionEquipo> ReporteActualizacionEquipo { get; set; }
        public virtual DbSet<ReporteVisita> ReporteVisita { get; set; }
        public virtual DbSet<ResponsableOrdenFabrica> ResponsableOrdenFabrica { get; set; }
        public virtual DbSet<RutaActualizacionEquipo> RutaActualizacionEquipo { get; set; }
        public virtual DbSet<Sede> Sede { get; set; }
        public virtual DbSet<SedesAsignadas> SedesAsignadas { get; set; }
        public virtual DbSet<Semana> Semana { get; set; }
        public virtual DbSet<SubModulos> SubModulos { get; set; }
        public virtual DbSet<TablaVentas> TablaVentas { get; set; }
        public virtual DbSet<TipoArticulo> TipoArticulo { get; set; }
        public virtual DbSet<TipoGasto> TipoGasto { get; set; }
        public virtual DbSet<TipoMedida> TipoMedida { get; set; }
        public virtual DbSet<TipoMerma> TipoMerma { get; set; }
        public virtual DbSet<TipoServicio> TipoServicio { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Traslados> Traslados { get; set; }
        public virtual DbSet<Tutoriales> Tutoriales { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Vendedor> Vendedor { get; set; }
        public virtual DbSet<VentaActiva> VentaActiva { get; set; }
        public virtual DbSet<VersionSoftware> VersionSoftware { get; set; }
        public virtual DbSet<BuscadorProducto> BuscadorProducto { get; set; }
        public virtual DbSet<R_DetalleVenta> R_DetalleVenta { get; set; }
        public virtual DbSet<R_PagoCredito> R_PagoCredito { get; set; }
        public virtual DbSet<V_ArchivoCompras> V_ArchivoCompras { get; set; }
        public virtual DbSet<v_CategoriaProducto> v_CategoriaProducto { get; set; }
        public virtual DbSet<V_Ciudades> V_Ciudades { get; set; }
        public virtual DbSet<V_Cliente> V_Cliente { get; set; }
        public virtual DbSet<V_Compras> V_Compras { get; set; }
        public virtual DbSet<V_CostoInventario> V_CostoInventario { get; set; }
        public virtual DbSet<V_CuentasPC> V_CuentasPC { get; set; }
        public virtual DbSet<V_DetalleCaja> V_DetalleCaja { get; set; }
        public virtual DbSet<V_DetalleCompra> V_DetalleCompra { get; set; }
        public virtual DbSet<V_DetallePedico_Venta> V_DetallePedico_Venta { get; set; }
        public virtual DbSet<V_DetallePedido> V_DetallePedido { get; set; }
        public virtual DbSet<V_DetalleTraslado> V_DetalleTraslado { get; set; }
        public virtual DbSet<V_FacturasCredito> V_FacturasCredito { get; set; }
        public virtual DbSet<V_Gastos> V_Gastos { get; set; }
        public virtual DbSet<V_InformeDetalleVenta> V_InformeDetalleVenta { get; set; }
        public virtual DbSet<V_Inventario> V_Inventario { get; set; }
        public virtual DbSet<V_InventarioTotal> V_InventarioTotal { get; set; }
        public virtual DbSet<V_LibroDiario> V_LibroDiario { get; set; }
        public virtual DbSet<V_ListaPrecio> V_ListaPrecio { get; set; }
        public virtual DbSet<V_ListaPrecios> V_ListaPrecios { get; set; }
        public virtual DbSet<V_ListaVentaCategoria> V_ListaVentaCategoria { get; set; }
        public virtual DbSet<V_Merma> V_Merma { get; set; }
        public virtual DbSet<V_PagoCP> V_PagoCP { get; set; }
        public virtual DbSet<V_PagosCreditoTienda> V_PagosCreditoTienda { get; set; }
        public virtual DbSet<V_pd> V_pd { get; set; }
        public virtual DbSet<V_Pedido> V_Pedido { get; set; }
        public virtual DbSet<V_Precios> V_Precios { get; set; }
        public virtual DbSet<V_Presentacion> V_Presentacion { get; set; }
        public virtual DbSet<V_Producto> V_Producto { get; set; }
        public virtual DbSet<v_productoVenta> v_productoVenta { get; set; }
        public virtual DbSet<V_Proveedor> V_Proveedor { get; set; }
        public virtual DbSet<V_R_VentaCliente> V_R_VentaCliente { get; set; }
        public virtual DbSet<V_Rutero> V_Rutero { get; set; }
        public virtual DbSet<V_SedesAsignadas> V_SedesAsignadas { get; set; }
        public virtual DbSet<V_TablaVentas> V_TablaVentas { get; set; }
        public virtual DbSet<V_TipoGasto> V_TipoGasto { get; set; }
        public virtual DbSet<V_TipoMedida> V_TipoMedida { get; set; }
        public virtual DbSet<V_TipoMerma> V_TipoMerma { get; set; }
        public virtual DbSet<V_TotalVentasDetalle> V_TotalVentasDetalle { get; set; }
        public virtual DbSet<V_Traslados> V_Traslados { get; set; }
        public virtual DbSet<v_Usuario> v_Usuario { get; set; }
        public virtual DbSet<V_Vendedor> V_Vendedor { get; set; }
    
        public virtual ObjectResult<CRUD_AdminControl_Result> CRUD_AdminControl(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_AdminControl_Result>("CRUD_AdminControl", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_ArchivoCompras_Result> CRUD_ArchivoCompras(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_ArchivoCompras_Result>("CRUD_ArchivoCompras", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_AutorizacionPC_Result> CRUD_AutorizacionPC(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_AutorizacionPC_Result>("CRUD_AutorizacionPC", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_BaseCaja_Result> CRUD_BaseCaja(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_BaseCaja_Result>("CRUD_BaseCaja", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_Bodega_Result> CRUD_Bodega(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_Bodega_Result>("CRUD_Bodega", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_CategoriaProducto_Result> CRUD_CategoriaProducto(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_CategoriaProducto_Result>("CRUD_CategoriaProducto", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_Clientes_Result> CRUD_Clientes(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_Clientes_Result>("CRUD_Clientes", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_Compras_Result> CRUD_Compras(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_Compras_Result>("CRUD_Compras", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_ConsecutivoFactura_Result> CRUD_ConsecutivoFactura(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_ConsecutivoFactura_Result>("CRUD_ConsecutivoFactura", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_ConsecutivoRecibo_Result> CRUD_ConsecutivoRecibo(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_ConsecutivoRecibo_Result>("CRUD_ConsecutivoRecibo", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_ConsecutivoVentaUsado_Result> CRUD_ConsecutivoVentaUsado(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_ConsecutivoVentaUsado_Result>("CRUD_ConsecutivoVentaUsado", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_DestapeProducto_Result> CRUD_DestapeProducto(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_DestapeProducto_Result>("CRUD_DestapeProducto", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_DetalleCompra_Result> CRUD_DetalleCompra(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_DetalleCompra_Result>("CRUD_DetalleCompra", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_DetalleOrdenFabrica_Result> CRUD_DetalleOrdenFabrica(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_DetalleOrdenFabrica_Result>("CRUD_DetalleOrdenFabrica", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_DetalleTraslado_Result> CRUD_DetalleTraslado(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_DetalleTraslado_Result>("CRUD_DetalleTraslado", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_DetalleVenta_Result> CRUD_DetalleVenta(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_DetalleVenta_Result>("CRUD_DetalleVenta", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_Gastos_Result> CRUD_Gastos(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_Gastos_Result>("CRUD_Gastos", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_GuidTraslados_Result> CRUD_GuidTraslados(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_GuidTraslados_Result>("CRUD_GuidTraslados", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_Inventario_Result> CRUD_Inventario(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_Inventario_Result>("CRUD_Inventario", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_InventarioTotal_Result> CRUD_InventarioTotal(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_InventarioTotal_Result>("CRUD_InventarioTotal", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_LibroDiario_Result> CRUD_LibroDiario(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_LibroDiario_Result>("CRUD_LibroDiario", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_Licencia_Result> CRUD_Licencia(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_Licencia_Result>("CRUD_Licencia", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_ListaPrecios_Result> CRUD_ListaPrecios(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_ListaPrecios_Result>("CRUD_ListaPrecios", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_Merma_Result> CRUD_Merma(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_Merma_Result>("CRUD_Merma", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_OrdenFabrica_Result> CRUD_OrdenFabrica(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_OrdenFabrica_Result>("CRUD_OrdenFabrica", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_OrdenServicio_Result> CRUD_OrdenServicio(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_OrdenServicio_Result>("CRUD_OrdenServicio", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_PagosCompras_Result> CRUD_PagosCompras(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_PagosCompras_Result>("CRUD_PagosCompras", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_PagosCreditoTienda_Result> CRUD_PagosCreditoTienda(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_PagosCreditoTienda_Result>("CRUD_PagosCreditoTienda", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_Pedidos_Result> CRUD_Pedidos(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_Pedidos_Result>("CRUD_Pedidos", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_Precios_Result> CRUD_Precios(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_Precios_Result>("CRUD_Precios", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_Presentacion_Result> CRUD_Presentacion(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_Presentacion_Result>("CRUD_Presentacion", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_Producto_Result> CRUD_Producto(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_Producto_Result>("CRUD_Producto", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_Proveedor_Result> CRUD_Proveedor(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_Proveedor_Result>("CRUD_Proveedor", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_R_ClienteVendedor_Result> CRUD_R_ClienteVendedor(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_R_ClienteVendedor_Result>("CRUD_R_ClienteVendedor", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_R_PedidoVenta_Result> CRUD_R_PedidoVenta(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_R_PedidoVenta_Result>("CRUD_R_PedidoVenta", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_R_VentaCliente_Result> CRUD_R_VentaCliente(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_R_VentaCliente_Result>("CRUD_R_VentaCliente", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_R_VentaUsuario_Result> CRUD_R_VentaUsuario(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_R_VentaUsuario_Result>("CRUD_R_VentaUsuario", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_ReporteActualizacionEquipo_Result> CRUD_ReporteActualizacionEquipo(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_ReporteActualizacionEquipo_Result>("CRUD_ReporteActualizacionEquipo", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_ResponsableOrdenFabrica_Result> CRUD_ResponsableOrdenFabrica(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_ResponsableOrdenFabrica_Result>("CRUD_ResponsableOrdenFabrica", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_RutaActualizacionEquipo_Result> CRUD_RutaActualizacionEquipo(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_RutaActualizacionEquipo_Result>("CRUD_RutaActualizacionEquipo", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_Sede_Result> CRUD_Sede(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_Sede_Result>("CRUD_Sede", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_SedesAsignadas_Result> CRUD_SedesAsignadas(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_SedesAsignadas_Result>("CRUD_SedesAsignadas", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_TablaVentas_Result> CRUD_TablaVentas(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_TablaVentas_Result>("CRUD_TablaVentas", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_TipoArticulo_Result> CRUD_TipoArticulo(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_TipoArticulo_Result>("CRUD_TipoArticulo", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_TipoGasto_Result> CRUD_TipoGasto(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_TipoGasto_Result>("CRUD_TipoGasto", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_TipoMedida_Result> CRUD_TipoMedida(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_TipoMedida_Result>("CRUD_TipoMedida", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_TipoMerma_Result> CRUD_TipoMerma(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_TipoMerma_Result>("CRUD_TipoMerma", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_TipoServicio_Result> CRUD_TipoServicio(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_TipoServicio_Result>("CRUD_TipoServicio", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_Traslados_Result> CRUD_Traslados(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_Traslados_Result>("CRUD_Traslados", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_Usuario_Result> CRUD_Usuario(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_Usuario_Result>("CRUD_Usuario", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_Vendedor_Result> CRUD_Vendedor(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_Vendedor_Result>("CRUD_Vendedor", jsonParameter, funcionParameter);
        }
    
        public virtual ObjectResult<CRUD_VersionSoftware_Result> CRUD_VersionSoftware(string json, Nullable<int> funcion)
        {
            var jsonParameter = json != null ?
                new ObjectParameter("json", json) :
                new ObjectParameter("json", typeof(string));
    
            var funcionParameter = funcion.HasValue ?
                new ObjectParameter("funcion", funcion) :
                new ObjectParameter("funcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_VersionSoftware_Result>("CRUD_VersionSoftware", jsonParameter, funcionParameter);
        }
    
        public virtual int EliminarArchivoComra(Nullable<int> idCompra)
        {
            var idCompraParameter = idCompra.HasValue ?
                new ObjectParameter("idCompra", idCompra) :
                new ObjectParameter("idCompra", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarArchivoComra", idCompraParameter);
        }
    
        public virtual int EliminarConsecutivoActivo(Nullable<int> idConsecutivo)
        {
            var idConsecutivoParameter = idConsecutivo.HasValue ?
                new ObjectParameter("idConsecutivo", idConsecutivo) :
                new ObjectParameter("idConsecutivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarConsecutivoActivo", idConsecutivoParameter);
        }
    
        public virtual int EliminarDetalleVEnta(Nullable<int> idVenta)
        {
            var idVentaParameter = idVenta.HasValue ?
                new ObjectParameter("idVenta", idVenta) :
                new ObjectParameter("idVenta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarDetalleVEnta", idVentaParameter);
        }
    
        public virtual int EliminarPagoCompras(Nullable<int> idCompra)
        {
            var idCompraParameter = idCompra.HasValue ?
                new ObjectParameter("idCompra", idCompra) :
                new ObjectParameter("idCompra", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarPagoCompras", idCompraParameter);
        }
    
        public virtual int EliminarPedido(Nullable<System.Guid> guidPedido)
        {
            var guidPedidoParameter = guidPedido.HasValue ?
                new ObjectParameter("guidPedido", guidPedido) :
                new ObjectParameter("guidPedido", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarPedido", guidPedidoParameter);
        }
    
        public virtual int EliminarVenta_app(Nullable<int> idVenta)
        {
            var idVentaParameter = idVenta.HasValue ?
                new ObjectParameter("idVenta", idVenta) :
                new ObjectParameter("idVenta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarVenta_app", idVentaParameter);
        }
    
        public virtual int EstadoVentaAnulado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EstadoVentaAnulado");
        }
    
        public virtual int EstadoVentaCancelado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EstadoVentaCancelado");
        }
    
        public virtual int EstadoVentaPendiente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EstadoVentaPendiente");
        }
    
        public virtual int FacturarPedido(Nullable<int> idVenta, Nullable<System.Guid> guid)
        {
            var idVentaParameter = idVenta.HasValue ?
                new ObjectParameter("idVenta", idVenta) :
                new ObjectParameter("idVenta", typeof(int));
    
            var guidParameter = guid.HasValue ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FacturarPedido", idVentaParameter, guidParameter);
        }
    
        public virtual ObjectResult<InformeVentasVendedor_dia_Result> InformeVentasVendedor_dia(Nullable<int> month, Nullable<int> day, Nullable<int> year)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var dayParameter = day.HasValue ?
                new ObjectParameter("day", day) :
                new ObjectParameter("day", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InformeVentasVendedor_dia_Result>("InformeVentasVendedor_dia", monthParameter, dayParameter, yearParameter);
        }
    
        public virtual ObjectResult<InformeVentasVendedor_mes_Result> InformeVentasVendedor_mes(Nullable<int> month, Nullable<int> year)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InformeVentasVendedor_mes_Result>("InformeVentasVendedor_mes", monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<InformeVentasVendedor_year_Result> InformeVentasVendedor_year(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InformeVentasVendedor_year_Result>("InformeVentasVendedor_year", yearParameter);
        }
    
        public virtual int insertAutorizacionFacturaElectronica(Nullable<int> idEmpresa, string prefijo, string resolucion, string fechaAvilitacion, string rango)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(int));
    
            var prefijoParameter = prefijo != null ?
                new ObjectParameter("prefijo", prefijo) :
                new ObjectParameter("prefijo", typeof(string));
    
            var resolucionParameter = resolucion != null ?
                new ObjectParameter("resolucion", resolucion) :
                new ObjectParameter("resolucion", typeof(string));
    
            var fechaAvilitacionParameter = fechaAvilitacion != null ?
                new ObjectParameter("fechaAvilitacion", fechaAvilitacion) :
                new ObjectParameter("fechaAvilitacion", typeof(string));
    
            var rangoParameter = rango != null ?
                new ObjectParameter("rango", rango) :
                new ObjectParameter("rango", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertAutorizacionFacturaElectronica", idEmpresaParameter, prefijoParameter, resolucionParameter, fechaAvilitacionParameter, rangoParameter);
        }
    
        public virtual int InsertMerma(Nullable<int> idTipoMerma, Nullable<int> idUsuario, Nullable<int> idInventarioTotal, Nullable<int> idInventario, Nullable<System.DateTime> fechaMerma, Nullable<decimal> cantidadMerma, string observacion)
        {
            var idTipoMermaParameter = idTipoMerma.HasValue ?
                new ObjectParameter("idTipoMerma", idTipoMerma) :
                new ObjectParameter("idTipoMerma", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var idInventarioTotalParameter = idInventarioTotal.HasValue ?
                new ObjectParameter("idInventarioTotal", idInventarioTotal) :
                new ObjectParameter("idInventarioTotal", typeof(int));
    
            var idInventarioParameter = idInventario.HasValue ?
                new ObjectParameter("idInventario", idInventario) :
                new ObjectParameter("idInventario", typeof(int));
    
            var fechaMermaParameter = fechaMerma.HasValue ?
                new ObjectParameter("fechaMerma", fechaMerma) :
                new ObjectParameter("fechaMerma", typeof(System.DateTime));
    
            var cantidadMermaParameter = cantidadMerma.HasValue ?
                new ObjectParameter("cantidadMerma", cantidadMerma) :
                new ObjectParameter("cantidadMerma", typeof(decimal));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("observacion", observacion) :
                new ObjectParameter("observacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertMerma", idTipoMermaParameter, idUsuarioParameter, idInventarioTotalParameter, idInventarioParameter, fechaMermaParameter, cantidadMermaParameter, observacionParameter);
        }
    
        public virtual ObjectResult<P_Rutero_Result> P_Rutero(Nullable<int> day, Nullable<int> month, Nullable<int> year)
        {
            var dayParameter = day.HasValue ?
                new ObjectParameter("day", day) :
                new ObjectParameter("day", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Rutero_Result>("P_Rutero", dayParameter, monthParameter, yearParameter);
        }
    
        public virtual int Reiniciar_DB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Reiniciar_DB");
        }
    
        public virtual ObjectResult<SelectAlistamiento_Result> SelectAlistamiento(Nullable<int> idVendedor, Nullable<int> idEstado, Nullable<int> day, Nullable<int> month, Nullable<int> year)
        {
            var idVendedorParameter = idVendedor.HasValue ?
                new ObjectParameter("idVendedor", idVendedor) :
                new ObjectParameter("idVendedor", typeof(int));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("idEstado", idEstado) :
                new ObjectParameter("idEstado", typeof(int));
    
            var dayParameter = day.HasValue ?
                new ObjectParameter("Day", day) :
                new ObjectParameter("Day", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAlistamiento_Result>("SelectAlistamiento", idVendedorParameter, idEstadoParameter, dayParameter, monthParameter, yearParameter);
        }
    
        public virtual int SumarGastosCajaDia(Nullable<System.DateTime> fechaApertura, Nullable<System.DateTime> fechaActual, Nullable<System.TimeSpan> horaApertura, Nullable<System.TimeSpan> horaActual, Nullable<int> bolsillo, ObjectParameter gasto)
        {
            var fechaAperturaParameter = fechaApertura.HasValue ?
                new ObjectParameter("FechaApertura", fechaApertura) :
                new ObjectParameter("FechaApertura", typeof(System.DateTime));
    
            var fechaActualParameter = fechaActual.HasValue ?
                new ObjectParameter("FechaActual", fechaActual) :
                new ObjectParameter("FechaActual", typeof(System.DateTime));
    
            var horaAperturaParameter = horaApertura.HasValue ?
                new ObjectParameter("HoraApertura", horaApertura) :
                new ObjectParameter("HoraApertura", typeof(System.TimeSpan));
    
            var horaActualParameter = horaActual.HasValue ?
                new ObjectParameter("HoraActual", horaActual) :
                new ObjectParameter("HoraActual", typeof(System.TimeSpan));
    
            var bolsilloParameter = bolsillo.HasValue ?
                new ObjectParameter("Bolsillo", bolsillo) :
                new ObjectParameter("Bolsillo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SumarGastosCajaDia", fechaAperturaParameter, fechaActualParameter, horaAperturaParameter, horaActualParameter, bolsilloParameter, gasto);
        }
    
        public virtual int V_ReiniciarDB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("V_ReiniciarDB");
        }
    }
}
