//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public Producto()
        //{
        //    this.DetalleCompra = new HashSet<DetalleCompra>();
        //    this.DetallePedido = new HashSet<DetallePedido>();
        //    this.Inventario = new HashSet<Inventario>();
        //    this.InventarioTotal = new HashSet<InventarioTotal>();
        //    this.Precios = new HashSet<Precios>();
        //}
    
        public int id { get; set; }
        public string codigoProducto { get; set; }
        public string descripcionProducto { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<int> idTipoMedida { get; set; }
        public Nullable<int> idEstadoAI { get; set; }
        public Nullable<System.Guid> guidProducto { get; set; }
        public Nullable<int> idSede { get; set; }
        public Nullable<int> eliminado { get; set; }
        public Nullable<int> gramera { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DetalleCompra> DetalleCompra { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DetallePedido> DetallePedido { get; set; }
        //public virtual EstadoAI EstadoAI { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Inventario> Inventario { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<InventarioTotal> InventarioTotal { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Precios> Precios { get; set; }
        //public virtual Sede Sede { get; set; }
        //public virtual TipoMedida TipoMedida { get; set; }
    }
}
