//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_DetalleVenta
    {
        public int idV { get; set; }
        public System.DateTime fechaVentaDetalleV { get; set; }
        public int idVentaV { get; set; }
        public string codigoProductoV { get; set; }
        public int idProductoDetalleVentaV { get; set; }
        public string descripcionProductoEditadaV { get; set; }
        public decimal precioProductoDetalleV { get; set; }
        public decimal cantidadDetalleVentaV { get; set; }
        public string letraTipoMedidaDetalleV { get; set; }
        public Nullable<decimal> totalDetalleVentaV { get; set; }
        public string tipoVentaDetalleV { get; set; }
        public string codigoProducto { get; set; }
        public Nullable<decimal> precioDetalleVentaV { get; set; }
        public string nombrePresentacion { get; set; }
    }
}
