//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_VentaCliente
    {
        public int id { get; set; }
        public int idVenta { get; set; }
        public int idCliente { get; set; }
        public Nullable<int> idSede { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Sede Sede { get; set; }
        public virtual TablaVentas TablaVentas { get; set; }
    }
}
