//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sede
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sede()
        {
            this.AutorizacionFacturacionElectronica = new HashSet<AutorizacionFacturacionElectronica>();
            this.BaseCaja = new HashSet<BaseCaja>();
            this.CategoriaProducto = new HashSet<CategoriaProducto>();
            this.Clientes = new HashSet<Clientes>();
            this.CompraActiva = new HashSet<CompraActiva>();
            this.Compras = new HashSet<Compras>();
            this.DetalleVenta = new HashSet<DetalleVenta>();
            this.Gastos = new HashSet<Gastos>();
            this.Inventario = new HashSet<Inventario>();
            this.InventarioTotal = new HashSet<InventarioTotal>();
            this.PagosCompras = new HashSet<PagosCompras>();
            this.PagosCreditoTienda = new HashSet<PagosCreditoTienda>();
            this.Producto = new HashSet<Producto>();
            this.R_VentaCliente = new HashSet<R_VentaCliente>();
            this.SedesAsignadas = new HashSet<SedesAsignadas>();
            this.TablaVentas = new HashSet<TablaVentas>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idusuario_creador { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> idusuario_modificacion { get; set; }
        public string nombreSede { get; set; }
        public string nit { get; set; }
        public string regimen { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public string direccion { get; set; }
        public string reprecentante { get; set; }
        public string nombre_impresora { get; set; }
        public string tipoImpresora { get; set; }
        public Nullable<int> tamañoPapel { get; set; }
        public string horarios_atencion { get; set; }
        public string cajon_monedero { get; set; }
        public string ruta_actualizacion { get; set; }
        public string ruta_carpeta { get; set; }
        public string imagenLogo { get; set; }
        public Nullable<int> id_tipoCaja { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public string codigoCajon { get; set; }
        public string correoAdmin1 { get; set; }
        public string leyenda2 { get; set; }
        public string tiendaOnline { get; set; }
        public Nullable<int> codigoImpresora { get; set; }
        public string leyenda1 { get; set; }
        public string impresora { get; set; }
        public Nullable<int> cortePapel { get; set; }
        public Nullable<int> aperturaCajon { get; set; }
        public Nullable<int> editarPrecioVentaProducto { get; set; }
        public Nullable<int> ventasEnNegativo { get; set; }
        public string resolucion { get; set; }
        public string fechaResolucion { get; set; }
        public string prefijoFectura { get; set; }
        public string rangoResolucion { get; set; }
        public string tipoFactura { get; set; }
        public Nullable<int> gramera { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorizacionFacturacionElectronica> AutorizacionFacturacionElectronica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaseCaja> BaseCaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriaProducto> CategoriaProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes> Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompraActiva> CompraActiva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compras> Compras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gastos> Gastos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioTotal> InventarioTotal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagosCompras> PagosCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagosCreditoTienda> PagosCreditoTienda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_VentaCliente> R_VentaCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SedesAsignadas> SedesAsignadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TablaVentas> TablaVentas { get; set; }
    }
}
