//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablaVentas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TablaVentas()
        {
            this.R_PedidoVenta = new HashSet<R_PedidoVenta>();
            this.R_VentaCliente = new HashSet<R_VentaCliente>();
            this.R_VentaVendedor = new HashSet<R_VentaVendedor>();
        }
    
        public int id { get; set; }
        public System.DateTime fechaVenta { get; set; }
        public string tipoFactura { get; set; }
        public int numeroVenta { get; set; }
        public decimal descuentoVenta { get; set; }
        public decimal ivaVenta { get; set; }
        public decimal efectivoVenta { get; set; }
        public decimal cambioVenta { get; set; }
        public string tipoVenta { get; set; }
        public string estadoVenta { get; set; }
        public string tipoPago { get; set; }
        public string numeroReferenciaPago { get; set; }
        public int idBaseCaja { get; set; }
        public Nullable<int> diasCredito { get; set; }
        public string fechaVencimiento { get; set; }
        public string observacionVenta { get; set; }
        public int IdSede { get; set; }
        public System.Guid guidVenta { get; set; }
        public decimal abonoTarjeta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_PedidoVenta> R_PedidoVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_VentaCliente> R_VentaCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_VentaVendedor> R_VentaVendedor { get; set; }
        public virtual Sede Sede { get; set; }
    }
}
