//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Merma = new HashSet<Merma>();
            this.R_VentaUsuario = new HashSet<R_VentaUsuario>();
            this.SedesAsignadas = new HashSet<SedesAsignadas>();
        }
    
        public int id { get; set; }
        public string identificacionUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public string telefonoUsuario { get; set; }
        public string cuentaUsuario { get; set; }
        public string claveUsuario { get; set; }
        public string estado_usuario { get; set; }
        public Nullable<int> idTipoUsuario { get; set; }
        public Nullable<int> idEstadoAI { get; set; }
    
        public virtual EstadoAI EstadoAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Merma> Merma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_VentaUsuario> R_VentaUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SedesAsignadas> SedesAsignadas { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
