//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Cliente
    {
        public int id { get; set; }
        public string nombreCliente { get; set; }
        public string razonSocialCliente { get; set; }
        public string documentoCliente { get; set; }
        public string direccionCliente { get; set; }
        public string telefonoCliente { get; set; }
        public string ciudadCliente { get; set; }
        public string barrioCliente { get; set; }
        public int idSede { get; set; }
        public string codigoCliente { get; set; }
        public string correo { get; set; }
    }
}
