//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Compras
    {
        public int idV { get; set; }
        public string facturaCompraV { get; set; }
        public Nullable<System.DateTime> fechaCompraV { get; set; }
        public Nullable<int> idProveedorV { get; set; }
        public string documentoProveedorV { get; set; }
        public Nullable<int> idSedeCompra { get; set; }
        public string nombreProveedorV { get; set; }
        public Nullable<decimal> subtotalCompraV { get; set; }
        public Nullable<decimal> ivaCompraV { get; set; }
        public Nullable<decimal> totalCompraV { get; set; }
        public Nullable<decimal> valorPagadoCompraV { get; set; }
        public Nullable<decimal> saldoCompraV { get; set; }
        public Nullable<int> idEstadoAI { get; set; }
    }
}
