//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DetalleCompra
    {
        public int id { get; set; }
        public int idCompra { get; set; }
        public Nullable<int> idInventarioTotal { get; set; }
        public int idInventario { get; set; }
        public int idPresentacion { get; set; }
        public string codigoProducto { get; set; }
        public string descripcionProducto { get; set; }
        public string nombrePresentacion { get; set; }
        public decimal contenidoPresentacion { get; set; }
        public Nullable<decimal> costoUnidad { get; set; }
        public decimal porcentajeIva { get; set; }
        public decimal porcentajeDescuento { get; set; }
        public decimal valorDescuento { get; set; }
        public decimal cantidad { get; set; }
        public decimal totalDetalle { get; set; }
        public Nullable<int> idSede { get; set; }
        public decimal precioUnitario { get; set; }
    }
}
