//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DetallePedido
    {
        public int id { get; set; }
        public System.Guid guidPedido { get; set; }
        public int idProducto { get; set; }
        public string codigoProducto { get; set; }
        public string descripcionProducto { get; set; }
        public decimal PrecioVenta { get; set; }
        public decimal cantidad { get; set; }
        public Nullable<decimal> total { get; set; }
    }
}
