//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_FacturasCredito
    {
        public int id { get; set; }
        public int idCliente { get; set; }
        public int idVenta { get; set; }
        public System.DateTime fechaVenta { get; set; }
        public string tipoFactura { get; set; }
        public int numeroVenta { get; set; }
        public Nullable<decimal> totalVenta { get; set; }
        public Nullable<decimal> totalPagadoVenta { get; set; }
        public Nullable<decimal> totalPendienteVenta { get; set; }
        public string estadoVenta { get; set; }
        public int IdSede { get; set; }
    }
}
