//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Inventario
    {
        public int id { get; set; }
        public int idProducto { get; set; }
        public int idPresentacion { get; set; }
        public string nombrePresentacion { get; set; }
        public decimal contenidoPresentacion { get; set; }
        public int idSede { get; set; }
        public Nullable<System.Guid> guidInventario { get; set; }
    }
}
