//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_InformeDetalleVenta
    {
        public int idV { get; set; }
        public System.DateTime fechaVentaDetalle { get; set; }
        public string tipoFacturaDetalle { get; set; }
        public int numeroFacturaDetalle { get; set; }
        public int idSedeDetalle { get; set; }
        public int idVentaV { get; set; }
        public string descripcionProductoEditadaV { get; set; }
        public decimal precioProductoV { get; set; }
        public decimal cantidadDetalleVentaV { get; set; }
        public Nullable<decimal> totalDetalleVentaV { get; set; }
    }
}
