//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ListaVentaCategoria
    {
        public int id_c { get; set; }
        public System.DateTime fechaVenta_c { get; set; }
        public int idSede_c { get; set; }
        public string nombreCategoria_c { get; set; }
        public string descripcionProducto_c { get; set; }
        public Nullable<decimal> costo_c { get; set; }
        public Nullable<decimal> precio_c { get; set; }
        public decimal cantidadDetalleVenta_c { get; set; }
        public Nullable<decimal> totalDetalleVenta_c { get; set; }
        public Nullable<int> idCategoria_c { get; set; }
    }
}
