//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LibroDiario
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fechaMovimiento { get; set; }
        public Nullable<int> idBolsillo { get; set; }
        public string nombreBolsillo { get; set; }
        public string motivoMovimiento { get; set; }
        public Nullable<decimal> debe { get; set; }
        public Nullable<decimal> haber { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public Nullable<decimal> saldoCaja { get; set; }
        public Nullable<decimal> saldoBanco { get; set; }
        public Nullable<decimal> saldoCajaMenor { get; set; }
        public Nullable<decimal> saldoTotal { get; set; }
    }
}
