//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Merma
    {
        public int id { get; set; }
        public System.DateTime fechaMerma { get; set; }
        public int idSede { get; set; }
        public int idTipoMerma { get; set; }
        public string nombreTipoMerma { get; set; }
        public int idUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public int idInventarioTotal { get; set; }
        public int idInventario { get; set; }
        public string codigoProducto { get; set; }
        public string descripcionProducto { get; set; }
        public string nombrePresentacion { get; set; }
        public decimal contenidoPresentacion { get; set; }
        public decimal cantidadMerma { get; set; }
        public Nullable<decimal> cantidadUnidad { get; set; }
        public string observacion { get; set; }
    }
}
