//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PagoCP
    {
        public int idVPagoCompra { get; set; }
        public int consecutivoVPagoCompra { get; set; }
        public Nullable<System.DateTime> FechaVPagoCompra { get; set; }
        public string facturaVPagoCompra { get; set; }
        public string proveedorVPagoCompra { get; set; }
        public Nullable<decimal> totalVPagoCompra { get; set; }
        public Nullable<decimal> totalPagadoVPagoCompra { get; set; }
        public Nullable<int> pagoActualVPagoCompra { get; set; }
        public Nullable<int> saldoVPagoCompra { get; set; }
        public Nullable<int> idBolsillo { get; set; }
        public string nombreBolsillo { get; set; }
        public Nullable<int> idBaseCaja { get; set; }
        public Nullable<int> IdSedePagoCompra { get; set; }
    }
}
