//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Pedido
    {
        public int id { get; set; }
        public System.Guid guidPedido { get; set; }
        public string guiaPedido { get; set; }
        public int idEstadoPedido { get; set; }
        public string nombreEstadoPedido { get; set; }
        public int idVendedor { get; set; }
        public string nombreVendedor { get; set; }
        public int idCliente { get; set; }
        public string nombreCliente { get; set; }
        public string telefonoCliente { get; set; }
        public System.DateTime fechaPedido { get; set; }
        public int diasEntrega { get; set; }
        public System.DateTime fechaEntrega { get; set; }
        public string observacionPedido { get; set; }
        public Nullable<decimal> totalPedido { get; set; }
        public string barrioCliente { get; set; }
        public string razonSocialCliente { get; set; }
    }
}
