//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Producto
    {
        public int id { get; set; }
        public Nullable<System.Guid> guidProducto { get; set; }
        public string codigoProducto { get; set; }
        public string descripcionProducto { get; set; }
        public Nullable<int> idTipoMedida { get; set; }
        public string nombreTipoMedida { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public string nombreCategoria { get; set; }
        public Nullable<int> idEstadoAI { get; set; }
        public string nombreEstadoAi { get; set; }
        public Nullable<int> idSede { get; set; }
        public Nullable<int> eliminado { get; set; }
    }
}
