//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Precios
    {
        public int id_v { get; set; }
        public int idProducto_v { get; set; }
        public int idInventario_v { get; set; }
        public int idListaPrecios_v { get; set; }
        public string nombreLista_v { get; set; }
        public Nullable<decimal> porcentajeUtilidad_v { get; set; }
        public decimal utilidad_v { get; set; }
        public decimal PrecioVenta_v { get; set; }
        public int idSede { get; set; }
    }
}
