//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_productoVenta
    {
        public int id { get; set; }
        public int idSede { get; set; }
        public Nullable<int> idTipoMedida { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public int idInventario { get; set; }
        public int idPrecios { get; set; }
        public string nombreSede { get; set; }
        public string nombreCategoria { get; set; }
        public Nullable<System.Guid> guidProducto { get; set; }
        public string codigoProducto { get; set; }
        public string descripcionProducto { get; set; }
        public string letraTipoMedida { get; set; }
        public string nombrePresentacion { get; set; }
        public Nullable<decimal> costoUnidadIT { get; set; }
        public Nullable<decimal> porcentajeIVAIT { get; set; }
        public decimal PrecioVenta { get; set; }
        public decimal inventarioActual { get; set; }
        public string nombreLista { get; set; }
        public int idListaPrecios { get; set; }
        public Nullable<int> idEstadoAI { get; set; }
        public int idPresentacion { get; set; }
        public Nullable<decimal> porcentajeUtilidad { get; set; }
        public decimal utilidad { get; set; }
        public int idInventarioTotal { get; set; }
        public decimal contenidoPresentacion { get; set; }
        public Nullable<decimal> stockInvetario { get; set; }
        public string estadoInventario { get; set; }
        public Nullable<decimal> porcentajeDescuento { get; set; }
        public Nullable<int> eliminado { get; set; }
        public Nullable<int> gramera { get; set; }
    }
}
