//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TablaVentas
    {
        public int id { get; set; }
        public System.DateTime fechaVenta { get; set; }
        public string tipoFactura { get; set; }
        public int numeroVenta { get; set; }
        public decimal descuentoVenta { get; set; }
        public Nullable<decimal> subtotalVenta { get; set; }
        public Nullable<decimal> basesIva { get; set; }
        public Nullable<decimal> ivaVenta { get; set; }
        public Nullable<decimal> totalVenta { get; set; }
        public decimal efectivoVenta { get; set; }
        public decimal cambioVenta { get; set; }
        public string tipoVenta { get; set; }
        public Nullable<decimal> totalPagadoVenta { get; set; }
        public Nullable<decimal> totalPendienteVenta { get; set; }
        public string estadoVenta { get; set; }
        public string tipoPago { get; set; }
        public string numeroReferenciaPago { get; set; }
        public int idBaseCaja { get; set; }
        public Nullable<int> diasCredito { get; set; }
        public string fechaVencimiento { get; set; }
        public string observacionVenta { get; set; }
        public int IdSede { get; set; }
        public System.Guid guidVenta { get; set; }
        public Nullable<decimal> costoTotalVenta { get; set; }
        public Nullable<decimal> utilidadTotalVenta { get; set; }
        public decimal abonoTarjeta { get; set; }
        public int idCliente { get; set; }
        public string nombreCliente { get; set; }
    }
}
